sales-manager-web/src/main/java/com/apuntesdejava/salesmanager/web/view/CategoryController.java
/*
 * Copyright 2021 Diego Silva <diego.silva at apuntesdejava.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.apuntesdejava.salesmanager.web.view;

import com.apuntesdejava.salesmanager.api.CategoryService;
import com.apuntesdejava.salesmanager.model.Category;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.ejb.EJB;
import org.primefaces.PrimeFaces;

/**
 *
 * @author Diego Silva <diego.silva at apuntesdejava.com>
 */
@Named(value = "categoryController")
@SessionScoped
public class CategoryController implements Serializable {

    @EJB
    private CategoryService service;

    private Category categoryCurrent;

    private List<Category> categoriesSelected;

    /**
     * Creates a new instance of CategoryController
     */
    public CategoryController() {
    }

    public List<Category> getCategoriesSelected() {
        return categoriesSelected;
    }

    public void setCategoriesSelected(List<Category> categoriesSelected) {
        this.categoriesSelected = categoriesSelected;
    }

    public List<Category> getCategoriesList() {
        return service.listAll();
    }

    public Category getCategoryCurrent() {
        return categoryCurrent;
    }

    public void setCategoryCurrent(Category categoryCurrent) {
        this.categoryCurrent = categoryCurrent;
    }

    public void categoryNewCommand() {
        categoryCurrent = new Category();
        PrimeFaces.current().dialog().openDynamic("/categories/form", Map.of("modal", true), null);
    }

    public void categoryDeleteCommand(Long id) {
        service.deleteById(id);
    }

    public void categoryEditCommand(Long id) {
        Optional<Category> opt = Optional.ofNullable(service.findById(id));
        if (opt.isPresent()) {
            categoryCurrent = opt.get();
            PrimeFaces.current().dialog().openDynamic("/categories/form", Map.of("modal", true), null);
        }
    }

    public void save() {
        if (categoryCurrent.getId() == 0) {
            var model = service.create(categoryCurrent);
            PrimeFaces.current().dialog().closeDynamic(model);
        } else {
            var model = service.update(categoryCurrent.getId(), categoryCurrent);
            PrimeFaces.current().dialog().closeDynamic(model);

        }

    }

}

sales-manager-web/src/main/java/com/apuntesdejava/salesmanager/web/view/MeasurementUnitController.java
package com.apuntesdejava.salesmanager.web.view;

/*
 * Copyright 2021 diego.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import com.apuntesdejava.salesmanager.api.MeasurementUnitService;
import com.apuntesdejava.salesmanager.model.MeasurementUnit;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 *
 * @author diego
 */
@Named
@SessionScoped
public class MeasurementUnitController implements Serializable {

    @EJB
    private MeasurementUnitService service;

    private MeasurementUnit currentUm;

    public List<MeasurementUnit> getMeasurementUnitList() {
        return service.listAll();
    }

    public MeasurementUnit getCurrentUm() {
        return currentUm;
    }

    public void setCurrentUm(MeasurementUnit currentUm) {
        this.currentUm = currentUm;
    }

    public String newMeasurementUnit() {
        currentUm = new MeasurementUnit();
        currentUm.setNewRecord(true);
        return "/measurement-unit/form";
    }

    public String save() {
        if (currentUm.isNewRecord()) {
            service.create(currentUm);
        } else {
            service.update(currentUm.getMeasurementId(), currentUm);
        }
        return "/measurement-unit/index";
    }

    public String edit() {
        String id = FacesContext
                .getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("id");
        currentUm = service.findById(id);
        return "/measurement-unit/form";
    }

    public String delete() {
        String id = FacesContext
                .getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("id");
        service.deleteById(id);
        return "/measurement-unit/index";
    }

}

sales-manager-web/src/main/java/com/apuntesdejava/salesmanager/web/view/ProductController.java
/*
 * Copyright 2021 diego.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.apuntesdejava.salesmanager.web.view;

import com.apuntesdejava.salesmanager.api.ProductService;
import com.apuntesdejava.salesmanager.model.Category;
import com.apuntesdejava.salesmanager.model.Product;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author diego
 */
@Named
@SessionScoped
public class ProductController implements Serializable {

    @EJB
    private ProductService productService;

    private Category categorySelected;

    private Product currentProduct;

    public List<Product> getProductsList() {
        var products = productService.listByCategory(categorySelected);
        return products;
    }

    public Category getCategorySelected() {
        return categorySelected;
    }

    public void setCategorySelected(Category categorySelected) {
        this.categorySelected = categorySelected;
    }

    public Product getCurrentProduct() {
        return currentProduct;
    }

    public void setCurrentProduct(Product currentProduct) {
        this.currentProduct = currentProduct;
    }

    public String newProductAction() {
        currentProduct = new Product();
        currentProduct.setCategory(categorySelected);
        return "/products/form";
    }

    public String save() {
        if (currentProduct.getId() == 0) {
            productService.create(currentProduct);
        }
        return "/products/index";
    }

}

sales-manager-web/src/main/java/com/apuntesdejava/salesmanager/web/view/ProductMovementController.java
/*
 * Copyright 2021 diego.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.apuntesdejava.salesmanager.web.view;

import com.apuntesdejava.salesmanager.api.ProductMovementService;
import com.apuntesdejava.salesmanager.api.ProductService;
import com.apuntesdejava.salesmanager.model.Product;
import com.apuntesdejava.salesmanager.model.ProductMovement;
import com.apuntesdejava.salesmanager.model.type.ProductMovementType;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.math.NumberUtils;
import org.primefaces.PrimeFaces;

/**
 *
 * @author diego
 */
@Named
@SessionScoped
public class ProductMovementController implements Serializable {

    private static final Logger LOG = Logger.getLogger(ProductMovementController.class.getName());

    @EJB
    private ProductMovementService productMovementService;
    @EJB
    private ProductService productService;
    private ProductMovement currentMovement;
    private Product currentProduct;

    public ProductMovement getCurrentMovement() {
        return currentMovement;
    }

    public void setCurrentMovement(ProductMovement currentMovement) {
        this.currentMovement = currentMovement;
    }

    public List<ProductMovement> getMovementsProductList() {
        return productMovementService.listByProduct(currentProduct);
    }

    public Product getCurrentProduct() {
        return currentProduct;
    }

    public void setCurrentProduct(Product currentProduct) {
        this.currentProduct = currentProduct;
    }

    public void addMovementAction() {
        LOG.log(Level.INFO, "-----> Producto asignar para movimiento:{0}", this.currentMovement);
        currentMovement = new ProductMovement();
        currentMovement.setProduct(currentProduct);
        PrimeFaces.current().dialog().openDynamic("/products/movement-form", Map.of("modal", true), null);
    }

    public void saveMovementAction() {
        currentMovement.setDate(LocalDateTime.now());
        var model = productMovementService.create(
                currentProduct,
                currentMovement.getCount(),
                currentMovement.getType(),
                currentMovement.getUnitPrice(),
                currentMovement.getStoreHouse(),
                currentMovement.getComment()
        );
        PrimeFaces.current().dialog().closeDynamic(model);
    }

    public List<ProductMovementType> getMovementTypes() {
        return Arrays.asList(ProductMovementType.values());
    }

    public String showMovements() {
        LOG.info("show movements");
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String productId = params.get("productId");
        if (StringUtils.isNotBlank(productId)) {
            Optional<Product> product = Optional.ofNullable(productService.findById(NumberUtils.toLong(productId)));
            if (product.isPresent()) {
                this.currentProduct = product.get();
                return "/products/movements";
            }
        }
        return null;
    }

}

sales-manager-web/src/main/java/com/apuntesdejava/salesmanager/web/view/StorehouseController.java
/*
 * Copyright 2021 diego.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.apuntesdejava.salesmanager.web.view;

import com.apuntesdejava.salesmanager.api.StorehouseService;
import com.apuntesdejava.salesmanager.model.Storehouse;
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import org.primefaces.PrimeFaces;

/**
 *
 * @author diego
 */
@Named
@SessionScoped
public class StorehouseController implements Serializable {

    @EJB
    private StorehouseService  storehouseService;

    private Storehouse storehouseSelected;

    public List<Storehouse> getStorehouseList() {
        return storehouseService.listAll();
    }

    public Storehouse getStorehouseSelected() {
        return storehouseSelected;
    }

    public void setStorehouseSelected(Storehouse storehouseSelected) {
        this.storehouseSelected = storehouseSelected;
    }

    public void storehouseNewCommand() {
        storehouseSelected = new Storehouse();
        PrimeFaces.current().dialog().openDynamic("/storehouses/form", Map.of("modal", true), null);
    }

    public void save() {
        if (storehouseSelected.getId() == 0) {
            var model = storehouseService.create(storehouseSelected);
            PrimeFaces.current().dialog().closeDynamic(model);
        } else {
            var model = storehouseService.update(storehouseSelected.getId(), storehouseSelected);
            PrimeFaces.current().dialog().closeDynamic(model);
        }
    }
}

sales-manager-web/src/main/webapp/products/form.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/WEB-INF/templates/sales-main.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui">
    <f:loadBundle var="msg" basename="/messages" />
    <ui:define name="title">
        #{msg.product_form_title}
    </ui:define>

    <ui:define name="content">
        <h:form id="form">
            <p:card>
                <f:facet name="title">
                    #{msg.product_form_title}
                </f:facet>

                <div class="form-group">
                    <p:outputLabel value="#{msg.product_name}" for="product_name" />
                    <p:inputText id="product_name" value="#{productController.currentProduct.name}" styleClass="form-control" />
                </div>
                <div class="form-group">
                    <p:outputLabel value="#{msg.product_description}" for="description" />
                    <p:inputTextarea  id="description" value="#{productController.currentProduct.description}" styleClass="form-control" rows="3" />
                </div>
                <div class="form-group">
                    <p:outputLabel for="@next" value="#{msg.product_category}"/>
                    <p:selectOneMenu styleClass="form-control" value="#{productController.currentProduct.category}" converter="#{categoryConverter}">
                        <f:selectItems value="#{categoryController.categoriesList}" var="cat" itemLabel="#{cat.name}" itemValue="#{cat}" />
                    </p:selectOneMenu>
                </div>
                <div class="form-group">
                    <p:outputLabel for="@next" value="#{msg.product_measurement_unit}"/>
                    <p:selectOneMenu styleClass="form-control" value="#{productController.currentProduct.measurementUnit}" converter="#{measurementUnitConverter}">
                        <f:selectItems value="#{measurementUnitController.measurementUnitList}" var="measure" itemLabel="#{measure.name}" itemValue="#{measure}" />
                    </p:selectOneMenu>
                </div>
                <f:facet name="footer">
                    <p:commandButton value="#{msg.save}"  action="#{productController.save}"/>
                </f:facet>
            </p:card>
        </h:form>
    </ui:define>

</ui:composition>

sales-manager-web/src/main/webapp/products/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/WEB-INF/templates/sales-main.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui">
    <f:loadBundle var="msg" basename="/messages" />
    <ui:define name="title">
        #{msg.products}
    </ui:define>
    <ui:define name="content">
        <p:card>
            <f:facet name="title"> #{msg.products}</f:facet>

            <h:form id="form">
                <p:toolbar>
                    <p:toolbarGroup>

                        <p:commandButton action="#{productController.newProductAction}" value="#{msg.product_new}" />
                    </p:toolbarGroup>
                </p:toolbar>

                <p:dataTable value="#{productController.productsList}" var="product" id="product" rowKey="#{product.id}">
                    <f:facet name="header">
                        <p:selectOneMenu value="#{productController.categorySelected}"  converter="#{categoryConverter}">
                            <f:selectItems value="#{categoryController.categoriesList}" var="cat" itemLabel="#{cat.name}" itemValue="#{cat}" />
                            <f:ajax render=":form:product"/>
                        </p:selectOneMenu>
                    </f:facet>
                    <p:column headerText="#{msg.product_name}">
                        #{product.name}
                    </p:column>
                    <p:column headerText="#{msg.product_measurement_unit}">
                        #{product.measurementUnit.name}
                    </p:column>
                    <p:column headerText="#{msg.product_count}">
                        #{product.totalCount}
                    </p:column>
                    <p:column>
                        <p:commandButton action="#{productMovementController.showMovements}" icon="pi pi-list" title="#{msg.product_movements}" >
                            <f:param name="productId" value="#{product.id}" />
                        </p:commandButton>
                    </p:column>
                </p:dataTable>
            </h:form>
        </p:card>
    </ui:define>

</ui:composition>

sales-manager-web/src/main/webapp/products/movement-form.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:loadBundle var="msg" basename="/messages" />
    <h:head>
        <title>#{msg.movement_form_title}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </h:head>
    <h:body>
        <h:form >
            <p:card>
                <div class="form-group">
                    <p:outputLabel value="#{msg.movement_product}" for="@next" />
                    <p:inputText value="#{productMovementController.currentMovement.product.name}" disabled="true"  styleClass="form-control form-control-lg"/>
                </div> 
                <div class="form-group">
                    <p:outputLabel for="@next" value="#{msg.movement_type}" />
                    <p:selectOneMenu value="#{productMovementController.currentMovement.type}" converter="#{movementTypeConverter}"  styleClass="form-control form-control-lg">
                        <f:selectItems value="#{productMovementController.movementTypes}" var="type" itemLabel="#{msg[type.label]}" itemValue="#{type}" />
                    </p:selectOneMenu>
                </div>  
                <div class="form-group">
                    <p:outputLabel for="@next" value="#{msg.movement_storehouse}" />
                    <p:selectOneMenu value="#{productMovementController.currentMovement.storeHouse}" converter="#{storehouseConverter}"  styleClass="form-control form-control-lg">
                        <f:selectItems value="#{storehouseController.storehouseList}" var="store" itemLabel="#{store.name}" itemValue="#{store}" />
                    </p:selectOneMenu>
                </div>  
                <div class=" row">
                    <div class="form-group col-6">
                        <p:outputLabel for="@next" value="#{msg.movement_count}" />
                        #{productMovementController.currentMovement.product.measurementUnit.name} 
                        <p:inputNumber  value="#{productMovementController.currentMovement.count}"  styleClass="form-control " minValue="0"/>
                    </div>  
                    <div class="form-group col-6">
                        <p:outputLabel for="@next" value="#{msg.movement_unitprice}" />
                        <p:inputNumber  value="#{productMovementController.currentMovement.unitPrice}"  styleClass="form-control  " minValue="0"/>
                    </div>  
                </div>
                <div class="form-group">
                    <p:outputLabel for="@next" value="#{msg.movement_comment}" />
                    <p:inputTextarea rows="3" value="#{productMovementController.currentMovement.comment}" required="true"  styleClass="form-control form-control-lg"/>
                </div>  
                <f:facet name="footer">
                    <p:commandButton value="#{msg.save}" action="#{productMovementController.saveMovementAction}" icon="fa fa-floppy-o"  />
                </f:facet>
            </p:card>
        </h:form>
    </h:body>
</html>

sales-manager-web/src/main/webapp/products/movements.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/WEB-INF/templates/sales-main.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui" >
    <f:loadBundle var="msg" basename="/messages" />
    <ui:define name="title">
        #{msg.product_movements_title}   #{productController.currentProduct.name}
    </ui:define>
    <ui:define name="content" >
        <h:form id="form">
            <p:card>
                <f:facet name="title">
                    #{msg.product_movements_title}   #{productMovementController.currentProduct.name}
                </f:facet>
                <p:toolbar>
                    <p:toolbarGroup>
                        <p:commandButton action="#{productMovementController.addMovementAction}" value="#{msg.movement_new}" >
                            <p:ajax event="dialogReturn"   update=":form:dt-movements" />
                        </p:commandButton>
                    </p:toolbarGroup>
                </p:toolbar>

                <p:dataTable id="dt-movements" value="#{productMovementController.movementsProductList}" var="mov" rowKey="#{mov.id}">
                    <p:column headerText="#{msg.movement_date}">
                        #{mov.date}
                    </p:column>
                    <p:column headerText="#{msg.movement_comment}">
                        #{mov.comment}
                    </p:column>
                    <p:column headerText="#{msg.movement_storehouse}">
                        #{mov.storeHouse.name}
                    </p:column>
                    <p:column headerText="#{msg.movement_type}">
                        #{mov.type}
                    </p:column>
                    <p:column headerText="#{msg.movement_count}">
                        #{mov.count}
                    </p:column>
                    <p:column headerText="#{msg.movement_unitprice}">
                        #{mov.unitPrice}
                    </p:column>
                </p:dataTable>
            </p:card>
        </h:form>
    </ui:define>

</ui:composition>